### ISSUE TITLE
Subtask - Modifizierung Aufgabenlisten Frontend

### ISSUE THREAD

**Issue by erikrei** [erikrei/ZahlenSchlau#58]
Eine neue Komponente `ChangeList.tsx` soll erstellt werden, in der der Benutzer seine Aufgabenlisten verändern kann.

- [x] Der Benutzer kann Aufgaben in der Aufgabenliste löschen
- [x] Der Benutzer kann Aufgaben in der Aufgabenliste hinzufügen
- [x] Der Benutzer kann die Liste komplett löschen.
- [x] Der Benutzer kann die Liste umbenennen.

Dabei sollten alle Fehlermöglichkeiten gedeckt sein, so dass keine Fehler bei der Anfrage ans Backend entstehen.

**Comment by erikrei** [comment]
Benutzer kann im Dashboard unter Aufgabenlisten die Listen direkt löschen und umbenennen. 
Spezifisches Feedback wurde bereits implementiert wie Name bereits vergeben, oder beim abbrechen des Löschens/Umbenennen.
